"""Executable skill: case-convert

Use this skill to convert an identifier between snake_case, camelCase, PascalCase, and kebab-case (to=snake|camel|pascal|kebab). Deterministic, offline. For code/config transforms.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = (kwargs.get("text", "") or "").strip()
    target = (kwargs.get("to") or "snake").lower()
    if not text:
        return {"status": "error", "result": {"reason": "text is required"}}
    words = re.findall(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z0-9]+|[A-Z]+", text.replace("-", " ").replace("_", " "))
    words = [w.lower() for w in words if w]
    if not words:
        return {"status": "error", "result": {"reason": "no word tokens found"}}
    if target == "camel":
        out = words[0] + "".join(w.capitalize() for w in words[1:])
    elif target == "pascal":
        out = "".join(w.capitalize() for w in words)
    elif target == "kebab":
        out = "-".join(words)
    else:
        out = "_".join(words)
    return {"status": "ok", "result": {"output": out, "case": target}}
