"""Executable skill: bytes-human

Use this skill to format a byte count as a human-readable size (B/KB/MB/GB/TB/PB). Deterministic, offline. For file sizes and quotas.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    try:
        n = float(kwargs.get("bytes"))
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "bytes must be numeric"}}
    neg = n < 0; n = abs(n)
    for unit in ("B", "KB", "MB", "GB", "TB", "PB"):
        if n < 1024 or unit == "PB":
            s = ("%d %s" % (n, unit)) if unit == "B" else ("%.2f %s" % (n, unit))
            return {"status": "ok", "result": {"human": ("-" + s) if neg else s}}
        n /= 1024.0
