"""Executable skill: seo-readability-scorer

Use this skill to score text for SEO readability: Flesch reading ease, avg sentence length, word count, passive-voice hints, and keyword density for a target keyword. Deterministic, offline, no dependencies. Great for grading blog drafts before publishing.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import re
import math
from collections import Counter

def skill(ctx, **kwargs):
    try:
        text = kwargs.get('text')
        keyword = kwargs.get('keyword')

        if not text:
            return {"status": "error", "result": {"reason": "Text is required"}}

        sentences = re.split(r'[.!?]', text)
        word_count = len(re.findall(r'\b\w+\b', text))
        avg_sentence_length = sum(len(re.findall(r'\b\w+\b', sentence)) for sentence in sentences) / len(sentences)
        flesch_reading_ease = 206.835 - 1.015 * (avg_sentence_length) - 84.6 * (word_count / len(sentences))

        passive_voice_hints = 0
        for sentence in sentences:
            words = re.findall(r'\b\w+\b', sentence)
            for i in range(len(words)):
                if words[i] in ['was', 'were', 'been', 'being'] and i < len(words) - 1 and words[i + 1] in ['by']:
                    passive_voice_hints += 1

        keyword_count = len(re.findall(r'\b' + re.escape(keyword) + r'\b', text, re.IGNORECASE)) if keyword else 0
        keyword_density = (keyword_count / word_count) * 100 if word_count > 0 else 0

        result = {
            'flesch_reading_ease': flesch_reading_ease,
            'avg_sentence_length': avg_sentence_length,
            'word_count': word_count,
            'passive_voice_hints': passive_voice_hints,
            'keyword_density': keyword_density,
        }

        return {"status": "ok", "result": result}

    except Exception as e:
        return {"status": "error", "result": {"reason": str(e)}}
