"""Executable skill: duplicate-sentences

Use this skill to detect repeated sentences in text (case/whitespace-insensitive) with their counts. Deterministic, offline. For catching LLM repetition and thin/padded content.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    seen, dups = {}, []
    for p in parts:
        key = re.sub(r"\s+", " ", p.strip().lower())
        if not key:
            continue
        seen[key] = seen.get(key, 0) + 1
    for key, c in seen.items():
        if c > 1:
            dups.append({"sentence": key, "count": c})
    return {"status": "ok", "result": {"duplicates": dups,
        "duplicate_count": len(dups), "clean": len(dups) == 0}}
