"""Executable skill: titlecase-headline

Use this skill to convert a string to AP-style headline title case: capitalizes the first and last word and all major words, but lowercases short articles/conjunctions/prepositions (a, an, the, and, of, to, etc.) when they fall mid-headline. Deterministic, offline. For post titles and headings.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    small = {"a","an","and","as","at","but","by","for","if","in","nor","of",
             "on","or","per","the","to","via","vs","with"}
    words = text.split()
    n = len(words)
    out = []
    for i, w in enumerate(words):
        core = w.lower()
        if i != 0 and i != n - 1 and core in small:
            out.append(core)
        else:
            out.append(w[:1].upper() + w[1:].lower() if w else w)
    return {"status": "ok", "result": {"headline": " ".join(out)}}
