"""Executable skill: simplify-text

Use this skill to rewrite complex text in plain, simple language at a roughly 8th-grade reading level while preserving meaning. Uses an LLM.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re


def skill(ctx, **kwargs):
    """
    Simplify complex text to an 8th-grade reading level using an LLM.
    
    Args:
        ctx: Runtime context with llm method
        **kwargs: Must include 'text' (string, required)
    
    Returns:
        {"status": "ok", "result": <simplified_text>} on success
        {"status": "error", "result": {"reason": "<why>"}} on error
    """
    # Validate required parameter
    text = kwargs.get("text")
    if text is None:
        return {
            "status": "error",
            "result": {"reason": "Missing required parameter: text"}
        }
    
    if not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' must be a string"}
        }
    
    if len(text.strip()) == 0:
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' cannot be empty"}
        }
    
    try:
        # Create a prompt that instructs the LLM to simplify text
        prompt = f"""Rewrite the following text in simple, clear language at roughly an 8th-grade reading level. Preserve all the meaning and important information, but use shorter sentences, simpler words, and clearer explanations. Do not add new information or change the core message.

Text to simplify:
{text}

Simplified version:"""
        
        # Call the LLM with a reasonable token limit
        simplified = ctx.llm(prompt, max_tokens=2000)
        
        # Normalize the response: strip leading/trailing whitespace
        simplified = simplified.strip()
        
        # Validate we got a meaningful result
        if not simplified or len(simplified) == 0:
            return {
                "status": "error",
                "result": {"reason": "LLM returned empty response"}
            }
        
        return {
            "status": "ok",
            "result": simplified
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to simplify text: {str(e)}"}
        }
