"""Executable skill: readability-grade

Use this skill to score text readability with the correct Flesch Reading Ease (0-100) and Flesch-Kincaid grade-level formulas, plus a plain-language difficulty band. Deterministic, offline, no dependencies. Grade a draft before publishing to check it matches your audience.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    words = re.findall(r"[A-Za-z][A-Za-z\x27]*", text)
    n_words = len(words)
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    n_sent = max(len(sentences), 1)
    def _syllables(w):
        w = w.lower()
        if not w:
            return 0
        groups = re.findall(r"[aeiouy]+", w)
        count = len(groups)
        if w.endswith("e") and not w.endswith("le") and count > 1:
            count -= 1
        return max(count, 1)
    n_syll = sum(_syllables(w) for w in words)
    if n_words == 0:
        return {"status": "error", "result": {"reason": "no words found"}}
    wps = n_words / n_sent
    spw = n_syll / n_words
    flesch = 206.835 - (1.015 * wps) - (84.6 * spw)
    grade = (0.39 * wps) + (11.8 * spw) - 15.59
    flesch = round(max(0.0, min(100.0, flesch)), 1)
    if flesch >= 70:
        band = "easy"
    elif flesch >= 50:
        band = "standard"
    elif flesch >= 30:
        band = "difficult"
    else:
        band = "very difficult"
    return {"status": "ok", "result": {
        "flesch_reading_ease": flesch,
        "flesch_kincaid_grade": round(max(0.0, grade), 1),
        "band": band,
        "words": n_words, "sentences": n_sent, "syllables": n_syll,
        "avg_words_per_sentence": round(wps, 2),
        "avg_syllables_per_word": round(spw, 2),
    }}
