"""Executable skill: dedupe-lines

Use this skill to remove duplicate lines from text, preserving first-seen order by default (optionally sorted or case-insensitive). Deterministic, offline. Returns the deduped text plus kept/removed counts.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    keep_order = kwargs.get("keep_order", True)
    ci = bool(kwargs.get("case_insensitive", False))
    lines = text.splitlines()
    seen, out = set(), []
    for ln in lines:
        key = ln.lower() if ci else ln
        if key not in seen:
            seen.add(key)
            out.append(ln)
    if not keep_order:
        out = sorted(out)
    return {"status": "ok", "result": {
        "text": "\n".join(out),
        "kept": len(out), "removed": len(lines) - len(out)}}
