"""Executable skill: format-price

Use this skill to format a numeric amount as a currency string with the correct symbol, thousands separators, and two decimals (USD, EUR, GBP, etc.). Handles ints, floats, and numeric strings. Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    amount = kwargs.get("amount")
    try:
        value = float(amount)
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "amount must be numeric"}}
    cur = (kwargs.get("currency") or "USD").upper()
    symbols = {"USD": "$", "EUR": "€", "GBP": "£", "JPY": "¥", "CAD": "$", "AUD": "$"}
    sym = symbols.get(cur, "")
    if cur == "JPY":
        body = "{:,.0f}".format(round(value))
    else:
        body = "{:,.2f}".format(value)
    formatted = (sym + body) if sym else (body + " " + cur)
    return {"status": "ok", "result": {"formatted": formatted, "currency": cur, "value": value}}
