"""Executable skill: html-to-text

Use this skill to convert HTML into clean plain text: removes script/style, turns block tags and <br> into newlines, strips remaining tags, unescapes HTML entities, and collapses whitespace. Deterministic, offline. The right first step before readability, word-count, or slop analysis on scraped or WordPress HTML.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re, html as _html
    src = kwargs.get("html", "")
    if not isinstance(src, str):
        return {"status": "error", "result": {"reason": "html must be a string"}}
    t = src
    t = re.sub(r"(?is)<(script|style)[^>]*>.*?</\1>", " ", t)  # drop script/style
    t = re.sub(r"(?i)<br\s*/?>", "\n", t)                       # br -> newline
    t = re.sub(r"(?i)</(p|div|li|h[1-6]|tr)>", "\n", t)         # block ends -> newline
    t = re.sub(r"<[^>]+>", "", t)                                # remaining tags
    t = _html.unescape(t)                                        # &amp; -> &
    t = re.sub(r"[ \t]+", " ", t)                               # collapse spaces
    t = re.sub(r"\n\s*\n\s*\n+", "\n\n", t)                # collapse blank lines
    t = "\n".join(line.strip() for line in t.split("\n")).strip()
    return {"status": "ok", "result": t}
