"""Executable skill: normalize-phone

Use this skill to normalize a phone number to E.164 format (+<country><number>): strips formatting, applies a default country code for bare 10-digit US numbers, preserves an explicit +prefix, and flags whether the result is a plausible length. Deterministic, offline. For cleaning contact/lead data.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    raw = kwargs.get("phone", "")
    if not isinstance(raw, str) or not raw.strip():
        return {"status": "error", "result": {"reason": "phone is required"}}
    default_cc = str(kwargs.get("default_country_code", "1"))
    had_plus = raw.strip().startswith("+")
    digits = re.sub(r"\D", "", raw)
    if not digits:
        return {"status": "error", "result": {"reason": "no digits in phone"}}
    if had_plus:
        e164 = "+" + digits
    elif len(digits) == 10:
        e164 = "+" + default_cc + digits
    elif digits.startswith(default_cc) and len(digits) == 10 + len(default_cc):
        e164 = "+" + digits
    else:
        e164 = "+" + digits
    valid = 8 <= len(re.sub(r"\D", "", e164)) <= 15
    return {"status": "ok", "result": {
        "e164": e164, "digits": digits, "valid": valid}}
