"""Executable skill: temperature-convert

Use this skill to convert a temperature between Celsius, Fahrenheit, and Kelvin (from_unit/to_unit = C/F/K). Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    try:
        v = float(kwargs.get("value"))
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "value must be numeric"}}
    frm = (kwargs.get("from_unit") or "C").upper()[0]
    to = (kwargs.get("to_unit") or "F").upper()[0]
    c = {"C": v, "F": (v - 32) * 5.0 / 9.0, "K": v - 273.15}.get(frm)
    if c is None:
        return {"status": "error", "result": {"reason": "from_unit must be C/F/K"}}
    out = {"C": c, "F": c * 9.0 / 5.0 + 32, "K": c + 273.15}.get(to)
    if out is None:
        return {"status": "error", "result": {"reason": "to_unit must be C/F/K"}}
    return {"status": "ok", "result": {"value": round(out, 2), "unit": to}}
