"""Executable skill: summarize-bullets

Use this skill to summarize a block of text into N concise bullet points capturing the key ideas. Uses an LLM. Good for TL;DRs and article recaps.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import re

def skill(ctx, **kwargs):
    text = kwargs.get("text")
    count = kwargs.get("count", 3)
    
    # Validate required parameters
    if not text or not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "text is required and must be a string"}
        }
    
    if not isinstance(count, (int, float)) or count <= 0:
        return {
            "status": "error",
            "result": {"reason": "count must be a positive number"}
        }
    
    count = int(count)
    
    try:
        # Call LLM to generate bullet points
        prompt = f"""Summarize the following text into exactly {count} concise bullet points capturing the key ideas. Each bullet should be clear and standalone.

Text to summarize:
{text}

Provide exactly {count} bullet points, one per line. Start each bullet with a dash (-) or asterisk (*). Do not include preamble or explanation."""
        
        response = ctx.llm(prompt, max_tokens=1000)
        
        # Parse and normalize the response
        if not response or not isinstance(response, str):
            return {
                "status": "error",
                "result": {"reason": "LLM returned invalid response"}
            }
        
        # Split by lines and clean
        lines = response.split("\n")
        bullets = []
        
        for line in lines:
            # Strip whitespace
            line = line.strip()
            
            # Skip empty lines and common preamble patterns
            if not line or line.lower().startswith("here are"):
                continue
            
            # Remove leading bullet markers (-, *, •, numbers followed by period/paren)
            cleaned = re.sub(r"^[\-\*•]\s*", "", line)
            cleaned = re.sub(r"^\d+[\.\)]\s*", "", cleaned)
            cleaned = cleaned.strip()
            
            # Skip lines that are too short or just markers
            if cleaned and len(cleaned) > 3:
                bullets.append(cleaned)
        
        # Enforce exact count by slicing
        bullets = bullets[:count]
        
        # Check if we got enough bullets
        if len(bullets) < count:
            return {
                "status": "error",
                "result": {"reason": f"Could not generate {count} bullet points from text"}
            }
        
        return {
            "status": "ok",
            "result": bullets
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to summarize text: {str(e)}"}
        }
