"""Executable skill: truncate-words

Use this skill to truncate text to a max number of words with an ellipsis (default 50). Deterministic, offline. For excerpts and previews.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    try:
        n = int(kwargs.get("words") or 50)
    except (TypeError, ValueError):
        n = 50
    words = text.split()
    if len(words) <= n:
        return {"status": "ok", "result": {"text": " ".join(words), "truncated": False}}
    return {"status": "ok", "result": {"text": " ".join(words[:n]) + "\u2026",
        "truncated": True, "word_count": n}}
