"""Executable skill: jaccard-similarity

Use this skill to measure word-set (Jaccard) similarity between two texts (0-1), with shared-word count and a near-duplicate flag (>=0.8). Deterministic, offline. For dedup and content-overlap detection.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    a = kwargs.get("text_a", ""); b = kwargs.get("text_b", "")
    if not isinstance(a, str) or not isinstance(b, str):
        return {"status": "error", "result": {"reason": "text_a and text_b must be strings"}}
    sa = set(re.findall(r"[a-z0-9]+", a.lower()))
    sb = set(re.findall(r"[a-z0-9]+", b.lower()))
    if not sa and not sb:
        return {"status": "ok", "result": {"similarity": 1.0, "shared": 0}}
    inter = sa & sb; union = sa | sb
    sim = len(inter) / len(union) if union else 0.0
    return {"status": "ok", "result": {"similarity": round(sim, 4),
        "shared": len(inter), "near_duplicate": sim >= 0.8}}
