"""Executable skill: extract-action-items

Use this skill to extract a clean list of concrete action items / to-dos from meeting notes or a message thread. Uses an LLM. Returns a list of short imperative tasks.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re


def skill(ctx, **kwargs):
    text = kwargs.get("text")
    
    if not text:
        return {
            "status": "error",
            "result": {"reason": "Missing required parameter: text"}
        }
    
    if not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' must be a string"}
        }
    
    try:
        prompt = f"""Extract all concrete action items / to-do tasks from the following text.
Return exactly a numbered list of short imperative tasks (e.g., "Fix the bug in login", "Schedule meeting with team").
Each task should be one line, starting with a number and period (1., 2., etc.).
Only include actionable items, not completed tasks or general discussion points.
Do not include preamble or explanations, only the numbered list.

Text:
{text}

Numbered action items:"""
        
        response = ctx.llm(prompt, max_tokens=1500)
        
        lines = response.split("\n")
        action_items = []
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            cleaned = re.sub(r"^[\d]+[\.\)]\s*", "", line)
            cleaned = re.sub(r"^[-•*]\s*", "", cleaned)
            cleaned = cleaned.strip()
            
            if cleaned and len(cleaned) > 0:
                action_items.append(cleaned)
        
        if not action_items:
            return {
                "status": "error",
                "result": {"reason": "No action items could be extracted from the provided text"}
            }
        
        return {
            "status": "ok",
            "result": action_items
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to extract action items: {str(e)}"}
        }
