"""Autogenerated CLI wrapper for the 'format-price' skill. Do not edit by hand."""
import argparse
import json
import sys

sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED")
sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\ATEN")


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [x.strip() for x in str(v).split(",") if x.strip()]


def _as_json(v):
    return v if isinstance(v, (dict, list)) else json.loads(v)


class _Ctx:
    """Minimal SkillContext shim (mirrors ATEN skill_library.context.SkillContext)."""
    niche = "reviews"
    agent_id = "cli"

    def llm(self, prompt, model="groq/llama-3.3-70b-versatile", max_tokens=1000):
        try:
            sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\cost-optimizer")
            from empire_router import router
            return router.complete(prompt=prompt, task="skill_llm", max_tokens=max_tokens)
        except Exception as e:
            print(f"[ctx.llm] {e}", file=sys.stderr)
            return ""

    def http_get(self, url, timeout=30):
        import urllib.request
        req = urllib.request.Request(url, headers={"User-Agent": "empire-skill/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return {"status": r.status, "body": r.read().decode("utf-8", "ignore")}


def main():
    ap = argparse.ArgumentParser(description='Use this skill to format a numeric amount as a currency string with the correct symbol, thousands separators, and two decimals (USD, EUR, GBP, etc.). Handles ints, floats, and numeric strings. Deterministic, offline.')
    ap.add_argument("--amount", default=None, required=True, help='The amount')
    ap.add_argument("--currency", default=None, required=False, help='ISO code (USD/EUR/GBP/JPY), default USD')
    args = ap.parse_args()
    kwargs = {}
    if getattr(args, "amount") is not None:
        kwargs["amount"] = float(getattr(args, "amount"))
    if getattr(args, "currency") is not None:
        kwargs["currency"] = str(getattr(args, "currency"))

    from format_price_skill import skill as _entry  # noqa
    result = _entry(_Ctx(), **kwargs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
