"""Executable skill: classify-sentiment

Use this skill to classify the sentiment of a short text as positive, negative, or neutral, with a one-line reason. Uses an LLM. For review/comment triage.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re

def skill(ctx, **kwargs):
    text = kwargs.get("text")
    
    if not text:
        return {
            "status": "error",
            "result": {"reason": "text parameter is required"}
        }
    
    if not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "text must be a string"}
        }
    
    text = text.strip()
    if not text:
        return {
            "status": "error",
            "result": {"reason": "text cannot be empty"}
        }
    
    try:
        prompt = f"""Classify the sentiment of the following text as exactly one of: positive, negative, or neutral.
Then provide a one-line reason for your classification.

Return your response in this exact JSON format:
{{"sentiment": "<positive|negative|neutral>", "reason": "<one-line explanation>"}}

Text to classify:
"{text}"

Respond with only the JSON, no other text."""
        
        response = ctx.llm(prompt, max_tokens=200)
        
        if not response:
            return {
                "status": "error",
                "result": {"reason": "LLM returned empty response"}
            }
        
        response = response.strip()
        
        json_match = re.search(r'\{.*\}', response, re.DOTALL)
        if not json_match:
            return {
                "status": "error",
                "result": {"reason": "Could not extract JSON from LLM response"}
            }
        
        json_str = json_match.group(0)
        parsed = json.loads(json_str)
        
        sentiment = parsed.get("sentiment", "").lower().strip()
        reason = parsed.get("reason", "").strip()
        
        if sentiment not in ["positive", "negative", "neutral"]:
            return {
                "status": "error",
                "result": {"reason": f"Invalid sentiment value: {sentiment}"}
            }
        
        if not reason:
            return {
                "status": "error",
                "result": {"reason": "Reason cannot be empty"}
            }
        
        return {
            "status": "ok",
            "result": {
                "sentiment": sentiment,
                "reason": reason
            }
        }
    
    except json.JSONDecodeError:
        return {
            "status": "error",
            "result": {"reason": "Failed to parse LLM response as JSON"}
        }
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Unexpected error: {str(e)}"}
        }
