"""Executable skill: meta-description

Use this skill to generate a clean SEO meta description from article body text: strips markdown/URLs, collapses whitespace, truncates to a max length (default 155) on a word boundary. Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    try:
        limit = int(kwargs.get("max_length") or 155)
    except (TypeError, ValueError):
        limit = 155
    t = re.sub(r"[#*_`>\[\]]", "", text)
    t = re.sub(r"https?://\S+", "", t)
    t = " ".join(t.split())
    if len(t) <= limit:
        desc = t
    else:
        cut = t[:limit - 1].rsplit(" ", 1)[0].rstrip(",.;:!?-")
        desc = (cut + "\u2026") if cut else t[:limit]
    return {"status": "ok", "result": {"meta_description": desc,
        "length": len(desc), "within_limit": len(desc) <= limit}}
