"""Executable skill: heading-outline

Use this skill to extract the heading outline (H1-H6) from markdown and check hierarchy health: flags multiple H1s and level jumps (H2->H4). Deterministic, offline. For SEO structure audits.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    md = kwargs.get("markdown", "")
    if not isinstance(md, str):
        return {"status": "error", "result": {"reason": "markdown must be a string"}}
    outline = []
    for line in md.splitlines():
        m = re.match(r"^(#{1,6})\s+(.*)", line.strip())
        if m:
            outline.append({"level": len(m.group(1)), "text": m.group(2).strip()})
    h1 = sum(1 for h in outline if h["level"] == 1)
    broken = False
    prev = 0
    for h in outline:
        if prev and h["level"] - prev > 1:
            broken = True
        prev = h["level"]
    return {"status": "ok", "result": {"outline": outline, "count": len(outline),
        "h1_count": h1, "hierarchy_ok": (not broken) and h1 <= 1}}
