"""Executable skill: answer-faq

Use this skill to generate a concise FAQ answer for a given question, optionally grounded in provided context text. Uses an LLM.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json

def skill(ctx, **kwargs):
    """
    Generate a concise FAQ answer for a given question, optionally grounded in context.
    """
    # Validate required parameters
    question = kwargs.get("question")
    if not question or not isinstance(question, str) or not question.strip():
        return {
            "status": "error",
            "result": {"reason": "question is required and must be a non-empty string"}
        }
    
    context = kwargs.get("context")
    if context is not None and not isinstance(context, str):
        return {
            "status": "error",
            "result": {"reason": "context must be a string if provided"}
        }
    
    try:
        # Build the prompt
        if context and context.strip():
            prompt = f"""You are an FAQ assistant. Based on the provided context, answer the following question concisely and clearly in 2-3 sentences.

Context:
{context}

Question: {question}

Answer:"""
        else:
            prompt = f"""You are an FAQ assistant. Answer the following question concisely and clearly in 2-3 sentences.

Question: {question}

Answer:"""
        
        # Call the LLM
        response = ctx.llm(prompt, max_tokens=500)
        
        # Normalize the response
        if not response or not isinstance(response, str):
            return {
                "status": "error",
                "result": {"reason": "LLM returned empty or invalid response"}
            }
        
        # Clean up the response
        answer = response.strip()
        
        if not answer:
            return {
                "status": "error",
                "result": {"reason": "LLM response was empty after normalization"}
            }
        
        return {
            "status": "ok",
            "result": {"answer": answer}
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to generate FAQ answer: {str(e)}"}
        }
