"""Executable skill: base64

Use this skill to base64-encode or -decode text (mode=encode|decode). Deterministic, offline. For tokens, data URIs, and encoding payloads.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import base64
    text = kwargs.get("text", "")
    mode = (kwargs.get("mode") or "encode").lower()
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    try:
        if mode == "decode":
            out = base64.b64decode(text.encode("utf-8"), validate=False).decode("utf-8", "replace")
        else:
            out = base64.b64encode(text.encode("utf-8")).decode("ascii")
    except Exception as e:
        return {"status": "error", "result": {"reason": "base64 %s failed: %s" % (mode, e)}}
    return {"status": "ok", "result": {"output": out, "mode": mode}}
