"""Executable skill: extract-json-block

Use this skill to pull the first valid JSON object or array out of noisy or LLM-generated text: strips ```json code fences, does a balanced-brace scan, and repairs trailing commas. Returns the parsed data. Deterministic, offline. Essential for safely parsing LLM output before using it.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import json, re
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    # 1) strip ```json ... ``` fences if present
    fence = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
    candidate = fence.group(1).strip() if fence else text
    # 2) try a straight parse
    for attempt in (candidate, text):
        try:
            return {"status": "ok", "result": {"data": json.loads(attempt), "repaired": False}}
        except Exception:
            pass
    # 3) balanced-brace/bracket scan for the first complete object or array
    def _scan(s, open_ch, close_ch):
        start = s.find(open_ch)
        if start < 0:
            return None
        depth = 0
        in_str = False
        esc = False
        for i in range(start, len(s)):
            c = s[i]
            if in_str:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == '"':
                    in_str = False
                continue
            if c == '"':
                in_str = True
            elif c == open_ch:
                depth += 1
            elif c == close_ch:
                depth -= 1
                if depth == 0:
                    return s[start:i + 1]
        return None
    for oc, cc in (("{", "}"), ("[", "]")):
        block = _scan(candidate, oc, cc)
        if not block:
            continue
        for repaired, txt in ((False, block),
                              (True, re.sub(r",(\s*[}\]])", r"\1", block))):
            try:
                return {"status": "ok", "result": {"data": json.loads(txt), "repaired": repaired}}
            except Exception:
                continue
    return {"status": "error", "result": {"reason": "no valid JSON block found"}}
