"""Executable skill: extract-numbers

Use this skill to pull all numbers (ints, decimals, thousands-separated) from text, with their sum. Deterministic, offline. For parsing prices, stats, and quantities out of copy.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    raw = re.findall(r"-?\d+(?:,\d{3})*(?:\.\d+)?", text)
    nums = []
    for r in raw:
        v = r.replace(",", "")
        nums.append(float(v) if "." in v else int(v))
    return {"status": "ok", "result": {"numbers": nums, "count": len(nums),
        "sum": sum(nums) if nums else 0}}
