"""Executable skill: reverse-string

Use this skill to reverse a string character by character. Deterministic offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    """Reverse a string character by character."""
    # Validate required parameter
    text = kwargs.get("text")
    if text is None:
        return {
            "status": "error",
            "result": {"reason": "Required parameter 'text' is missing"}
        }
    
    # Ensure text is a string
    if not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' must be a string"}
        }
    
    try:
        # Reverse the string
        reversed_text = text[::-1]
        return {
            "status": "ok",
            "result": reversed_text
        }
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to reverse string: {str(e)}"}
        }
