"""Executable skill: chunk-list

Use this skill to split a list (or comma string) into fixed-size chunks. Deterministic, offline. For batching, pagination, grid layouts.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    items = kwargs.get("items")
    if isinstance(items, str):
        items = [x.strip() for x in items.split(",") if x.strip()]
    if not isinstance(items, list):
        return {"status": "error", "result": {"reason": "items must be a list or comma string"}}
    try:
        size = int(kwargs.get("size") or 3)
    except (TypeError, ValueError):
        size = 3
    if size < 1:
        size = 1
    chunks = [items[i:i + size] for i in range(0, len(items), size)]
    return {"status": "ok", "result": {"chunks": chunks, "count": len(chunks), "size": size}}
