"""Executable skill: email-subject-lines

Use this skill to generate N catchy email subject lines from an email body or topic, optimized for open rate (curiosity, brevity, no spam words). Uses an LLM. Returns a list.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re


def skill(ctx, **kwargs):
    """
    Generate N catchy email subject lines from email body or topic.
    Optimized for open rate (curiosity, brevity, no spam words).
    """
    
    # Validate required parameters
    text = kwargs.get("text")
    if not text or not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' is required and must be a non-empty string"}
        }
    
    # Get optional count parameter
    count = kwargs.get("count", 5)
    try:
        count = int(count)
        if count < 1:
            count = 5
    except (TypeError, ValueError):
        count = 5
    
    # Ensure count is reasonable
    if count > 20:
        count = 20
    
    try:
        # Build prompt for LLM
        prompt = f"""You are an expert email marketing strategist. Generate exactly {count} catchy, concise email subject lines from the following email body or topic.

Requirements for each subject line:
- Maximum 60 characters
- Optimized for high open rates
- Create curiosity or urgency without being clickbait
- Avoid spam trigger words (FREE, URGENT, ACT NOW, LIMITED TIME, $$, etc.)
- No emojis
- No all caps
- Clear and relevant to the content

Email body or topic:
{text}

Generate exactly {count} subject lines. Output ONLY the subject lines, one per line, numbered 1-{count}. Do not include any other text or explanation."""
        
        # Call LLM
        response = ctx.llm(prompt, max_tokens=1000)
        
        if not response:
            return {
                "status": "error",
                "result": {"reason": "LLM returned empty response"}
            }
        
        # Parse the response to extract subject lines
        lines = response.strip().split("\n")
        subject_lines = []
        
        for line in lines:
            line = line.strip()
            
            # Skip empty lines and lines that are just explanatory text
            if not line or line.lower().startswith("here"):
                continue
            
            # Remove leading numbers and punctuation (e.g., "1.", "1)", "1 -")
            cleaned = re.sub(r"^[\d]+[\.\):\-\s]+", "", line).strip()
            
            # Skip if empty after cleaning
            if not cleaned:
                continue
            
            # Skip lines that look like instructions or meta-text
            if cleaned.lower().startswith("subject line") or len(cleaned) < 5:
                continue
            
            # Ensure it's not too long
            if len(cleaned) <= 100:
                subject_lines.append(cleaned)
        
        # Enforce exact count
        subject_lines = subject_lines[:count]
        
        # Check if we have enough valid subject lines
        if not subject_lines:
            return {
                "status": "error",
                "result": {"reason": "Could not parse valid subject lines from LLM response"}
            }
        
        return {
            "status": "ok",
            "result": subject_lines
        }
        
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Failed to generate subject lines: {str(e)}"}
        }
