"""Executable skill: generate-cta

Use this skill to generate N compelling call-to-action lines for a given product or offer description. Uses an LLM. Returns a list of CTA options.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re

def skill(ctx, **kwargs):
    # Validate required parameters
    text = kwargs.get("text")
    if not text or not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' is required and must be a non-empty string"}
        }
    
    # Get optional count parameter, default to 5
    count = kwargs.get("count", 5)
    try:
        count = int(count)
        if count < 1:
            count = 5
    except (ValueError, TypeError):
        count = 5
    
    # Construct the prompt for the LLM
    prompt = f"""Generate exactly {count} compelling call-to-action (CTA) lines for the following product or offer description.

Product/Offer Description:
{text}

Requirements:
- Generate exactly {count} CTAs
- Each CTA should be a single line, punchy and action-oriented
- CTAs should be varied in style and approach
- Make them compelling and conversion-focused

Output format: Return only the CTA lines, one per line. Do not include numbering, bullet points, preamble, or explanations."""
    
    try:
        response = ctx.llm(prompt, max_tokens=1000)
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"LLM call failed: {str(e)}"}
        }
    
    if not response:
        return {
            "status": "error",
            "result": {"reason": "LLM returned empty response"}
        }
    
    # Parse and normalize the response
    lines = response.strip().split("\n")
    ctas = []
    
    for line in lines:
        # Strip whitespace
        line = line.strip()
        
        # Skip empty lines
        if not line:
            continue
        
        # Remove common prefixes (bullets, numbering, etc.)
        line = re.sub(r"^[\d]+[\.\)\-\s]+", "", line)  # Remove "1. " or "1) " or "1- "
        line = re.sub(r"^[\*\•\-\s]+", "", line)  # Remove bullets
        line = line.strip()
        
        # Skip lines that look like preamble
        if line.lower().startswith("here") or line.lower().startswith("cta") or len(line) < 5:
            continue
        
        ctas.append(line)
    
    # Ensure we have exactly the requested count
    ctas = ctas[:count]
    
    # If we don't have enough CTAs, return error
    if len(ctas) == 0:
        return {
            "status": "error",
            "result": {"reason": "Could not parse any valid CTAs from LLM response"}
        }
    
    return {
        "status": "ok",
        "result": ctas
    }
