"""Executable skill: keyword-seo-check

Use this skill to check whether a target keyword appears in the title and slug (and at the title start) and returns an SEO placement score. Deterministic, offline. For on-page SEO validation.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    kw = (kwargs.get("keyword", "") or "").strip().lower()
    title = (kwargs.get("title", "") or "").lower()
    slug = (kwargs.get("slug", "") or "").lower()
    if not kw:
        return {"status": "error", "result": {"reason": "keyword is required"}}
    kw_slug = re.sub(r"[^a-z0-9]+", "-", kw).strip("-")
    in_title = kw in title
    in_slug = kw_slug in slug
    title_start = title.strip().startswith(kw)
    score = sum([in_title, in_slug, title_start])
    return {"status": "ok", "result": {
        "in_title": in_title, "in_slug": in_slug,
        "keyword_at_title_start": title_start,
        "seo_score": score, "max_score": 3,
        "passed": in_title and in_slug}}
