"""Executable skill: ordinal

Use this skill to convert an integer to its ordinal string (1->1st, 22->22nd, 113->113th). Deterministic, offline. For ranks and dates.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    try:
        n = int(kwargs.get("number"))
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "number must be an integer"}}
    if 10 <= abs(n) % 100 <= 20:
        suf = "th"
    else:
        suf = {1: "st", 2: "nd", 3: "rd"}.get(abs(n) % 10, "th")
    return {"status": "ok", "result": {"ordinal": "%d%s" % (n, suf)}}
