"""Executable skill: slugify

Use this skill whenever you need to convert an arbitrary string into a clean URL slug: lowercase, non-alphanumerics to single hyphens, collapse repeats, trim, optional max length on a word boundary. Deterministic, offline, no dependencies.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    max_length = kwargs.get("max_length")
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    if max_length:
        try:
            n = int(max_length)
            if len(slug) > n:
                cut = slug[:n].rsplit("-", 1)[0] or slug[:n]
                slug = cut.strip("-")
        except (TypeError, ValueError):
            pass
    return {"status": "ok", "result": slug}
