"""Executable skill: csv-column

Use this skill to extract a single column's values from CSV text by header name or index. Deterministic, offline. For pulling one field out of a spreadsheet export.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import csv, io
    text = kwargs.get("csv", ""); col = kwargs.get("column", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "csv is required"}}
    if col in (None, ""):
        return {"status": "error", "result": {"reason": "column is required"}}
    reader = csv.reader(io.StringIO(text))
    rows = [r for r in reader if r]
    if not rows:
        return {"status": "ok", "result": {"values": [], "count": 0}}
    header = [h.strip() for h in rows[0]]
    idx = None
    if str(col).isdigit():
        idx = int(col)
    elif str(col) in header:
        idx = header.index(str(col))
    if idx is None or idx >= len(header):
        return {"status": "error", "result": {"reason": "column not found: %s" % col}}
    vals = [r[idx] for r in rows[1:] if idx < len(r)]
    return {"status": "ok", "result": {"values": vals, "count": len(vals),
        "column": header[idx]}}
