"""Executable skill: percent-change

Use this skill to compute the percentage change from an old value to a new value, plus absolute change and direction. Handles old=0. Deterministic, offline. For metrics/analytics.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    try:
        old = float(kwargs.get("old"))
        new = float(kwargs.get("new"))
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "old and new must be numeric"}}
    if old == 0:
        return {"status": "ok", "result": {"pct_change": None, "direction": "n/a",
            "note": "old value is 0; percent change undefined", "abs_change": new - old}}
    pct = (new - old) / abs(old) * 100.0
    return {"status": "ok", "result": {
        "pct_change": round(pct, 2),
        "abs_change": round(new - old, 6),
        "direction": "up" if pct > 0 else "down" if pct < 0 else "flat"}}
