"""Executable skill: extract-emails

Use this skill to extract all valid email addresses from arbitrary text, de-duplicated and lowercased. Uses RFC-ish validation. Deterministic, offline. Useful for parsing scraped pages, contact forms, or documents for leads.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    pattern = r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"
    found = re.findall(pattern, text)
    seen, emails = set(), []
    for e in found:
        lo = e.lower()
        if lo not in seen:
            seen.add(lo)
            emails.append(lo)
    return {"status": "ok", "result": {"emails": emails, "count": len(emails)}}
