"""Executable skill: mask-secrets

Use this skill to redact secrets from text before logging or sharing: masks OpenAI keys (sk-), GitHub PATs, AWS access keys, Slack tokens, Bearer tokens, and email addresses. Deterministic, offline. Returns the masked text and a redaction count.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    patterns = [
        (r"(sk-[A-Za-z0-9]{8,})", "sk-***"),
        (r"(github_pat_[A-Za-z0-9_]{8,})", "github_pat_***"),
        (r"(gh[pousr]_[A-Za-z0-9]{8,})", "gh*_***"),
        (r"(AKIA[0-9A-Z]{12,})", "AKIA***"),
        (r"(xox[baprs]-[A-Za-z0-9-]{8,})", "xox*-***"),
        (r"(Bearer\s+)[A-Za-z0-9._\-]{12,}", r"\1***"),
        (r"([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+\.[A-Za-z]{2,})", r"***@\2"),
    ]
    masked = text
    total = 0
    for pat, repl in patterns:
        masked, n = re.subn(pat, repl, masked)
        total += n
    return {"status": "ok", "result": {"masked": masked, "redactions": total}}
