"""Executable skill: title-to-path

Use this skill to turn a title or breadcrumb (split on / \ > | or arrows) into a clean lowercase URL path with slugged segments. Deterministic, offline. For building nested URLs from titles.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    parts = [p for p in re.split(r"[\\/>|\u2192]+", text) if p.strip()]
    slugged = []
    for p in parts:
        s = re.sub(r"[^a-z0-9]+", "-", p.strip().lower()).strip("-")
        if s:
            slugged.append(s)
    return {"status": "ok", "result": {"path": "/".join(slugged), "segments": slugged}}
