"""Executable skill: link-audit

Use this skill to audit markdown links: counts internal vs external (by site_domain) and checks the 3-5 internal-links-per-post convention. Deterministic, offline. For SEO link hygiene.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    md = kwargs.get("markdown", "")
    if not isinstance(md, str):
        return {"status": "error", "result": {"reason": "markdown must be a string"}}
    domain = (kwargs.get("site_domain", "") or "").lower().replace("www.", "")
    links = re.findall(r"\[[^\]]*\]\(([^)]+)\)", md)
    internal, external = 0, 0
    for url in links:
        u = url.strip().lower()
        if u.startswith("http"):
            if domain and domain in u:
                internal += 1
            else:
                external += 1
        else:
            internal += 1
    return {"status": "ok", "result": {"total_links": len(links),
        "internal": internal, "external": external,
        "internal_ok": 3 <= internal <= 5}}
