"""Executable skill: content-stats

Use this skill to get objective stats for a piece of text: word count, character count, sentence count, paragraph count, and estimated reading time in minutes (at 220 wpm). Deterministic, offline, no dependencies. Good for grading draft length before publishing.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    words = re.findall(r"\b\w+\b", text)
    word_count = len(words)
    sentences = len([s for s in re.split(r"[.!?]+", text) if s.strip()])
    paragraphs = len([p for p in re.split(r"\n\s*\n", text) if p.strip()])
    try:
        wpm = float(kwargs.get("wpm") or 220)
        if wpm <= 0:
            wpm = 220.0
    except (TypeError, ValueError):
        wpm = 220.0
    reading_minutes = round(word_count / wpm, 1) if word_count else 0.0
    return {"status": "ok", "result": {
        "word_count": word_count,
        "character_count": len(text),
        "character_count_no_spaces": len(re.sub(r"\s", "", text)),
        "sentence_count": sentences,
        "paragraph_count": max(paragraphs, 1 if text.strip() else 0),
        "reading_time_minutes": reading_minutes,
    }}
