"""Executable skill: utm-report

Use this skill to audit a batch of URLs for campaign attribution: parses UTM parameters from every URL, flags untagged links, and aggregates counts by source and by campaign. Deterministic, offline. Feed it your link list and get an attribution-readiness report.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    from urllib.parse import urlparse, parse_qsl
    urls = kwargs.get("urls")
    if isinstance(urls, str):
        urls = [u.strip() for u in urls.splitlines() if u.strip()]
    if not isinstance(urls, list) or not urls:
        return {"status": "error", "result": {"reason": "urls (list or newline string) is required"}}
    keys = ("utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content")
    rows, missing, by_source, by_campaign = [], [], {}, {}
    for u in urls:
        try:
            q = dict(parse_qsl(urlparse(u).query))
        except Exception:
            missing.append(u)
            continue
        tags = {k: q.get(k) for k in keys if q.get(k)}
        if not tags.get("utm_source"):
            missing.append(u)
        else:
            by_source[tags["utm_source"]] = by_source.get(tags["utm_source"], 0) + 1
            if tags.get("utm_campaign"):
                c = tags["utm_campaign"]
                by_campaign[c] = by_campaign.get(c, 0) + 1
        rows.append({"url": u, "tags": tags})
    return {"status": "ok", "result": {
        "total": len(urls),
        "tagged": len(urls) - len(missing),
        "untagged": missing,
        "by_source": dict(sorted(by_source.items(), key=lambda x: -x[1])),
        "by_campaign": dict(sorted(by_campaign.items(), key=lambda x: -x[1])),
        "rows": rows,
    }}
