"""Executable skill: split-sentences

Use this skill to split text into sentences (on . ! ? followed by a capital/quote). Deterministic, offline. For readability, summarization prep, and per-sentence processing.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"\u201c])", text.strip())
    sents = [p.strip() for p in parts if p.strip()]
    return {"status": "ok", "result": {"sentences": sents, "count": len(sents)}}
