"""Executable skill: tone-check

Use this skill to assess the tone of a text (e.g. professional, casual, aggressive, warm) and flag any tone that clashes with a stated target tone. Uses an LLM. For brand-voice QA.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re

def skill(ctx, **kwargs):
    text = kwargs.get("text")
    target_tone = kwargs.get("target_tone", "")
    
    if not text or not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "Missing or invalid required parameter: text"}}
    
    if not target_tone or not isinstance(target_tone, str):
        return {"status": "error", "result": {"reason": "Missing or invalid required parameter: target_tone"}}
    
    try:
        prompt = f"""Assess the tone of the following text and compare it to the target tone: '{target_tone}'.

Return your analysis in this exact format with no additional text:
ASSESSED_TONE: <one or two words describing the primary tone>
SCORE: <integer from 1 to 10 where 1=very mismatched and 10=perfectly aligned>
ISSUES: <comma-separated list of specific tone clashes or 'None' if no issues>
EXPLANATION: <one sentence explaining the main finding>

Text to analyze:
{text}

Target tone: {target_tone}
"""
        
        response = ctx.llm(prompt, max_tokens=500)
        if not response:
            return {"status": "error", "result": {"reason": "Failed to get tone analysis response from LLM"}}
        
        lines = response.strip().split('\n')
        assessed_tone = ""
        score = 0
        issues_raw = ""
        explanation = ""
        
        for line in lines:
            line = line.strip()
            if line.startswith("ASSESSED_TONE:"):
                assessed_tone = line[len("ASSESSED_TONE:"):].strip()
            elif line.startswith("SCORE:"):
                score_text = line[len("SCORE:"):].strip()
                try:
                    score = int(score_text)
                    score = max(1, min(10, score))
                except ValueError:
                    score = 5
            elif line.startswith("ISSUES:"):
                issues_raw = line[len("ISSUES:"):].strip()
            elif line.startswith("EXPLANATION:"):
                explanation = line[len("EXPLANATION:"):].strip()
        
        if not assessed_tone:
            return {"status": "error", "result": {"reason": "Could not parse assessed tone from LLM response"}}
        
        issues = []
        if issues_raw.lower() != "none":
            issues = [issue.strip() for issue in issues_raw.split(',') if issue.strip()]
        
        is_consistent = score >= 7
        clash_detected = not is_consistent and len(issues) > 0
        
        result = {
            "text_snippet": text[:100] if len(text) > 100 else text,
            "target_tone": target_tone,
            "assessed_tone": assessed_tone,
            "tone_alignment_score": score,
            "is_consistent": is_consistent,
            "clash_detected": clash_detected,
            "issues": issues,
            "explanation": explanation
        }
        
        return {"status": "ok", "result": result}
        
    except Exception as e:
        return {"status": "error", "result": {"reason": f"Error during tone analysis: {str(e)}"}}
