"""Executable skill: parse-any-date

Use this skill to parse a date/time from almost any format (ISO 8601, GMT/RFC, epoch seconds or millis, common US/EU formats), normalize it to UTC, and get a humanized 'time ago' string plus age in hours. Deterministic, offline. Handles the messy timestamps agents get from APIs and scraped pages.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    from datetime import datetime, timezone
    value = kwargs.get("value", "")
    if value in (None, ""):
        return {"status": "error", "result": {"reason": "value is required"}}
    s = str(value).strip()
    dt = None
    # epoch seconds/millis
    try:
        num = float(s)
        if num > 1e12:
            num = num / 1000.0
        dt = datetime.fromtimestamp(num, tz=timezone.utc)
    except (TypeError, ValueError):
        pass
    if dt is None:
        iso = s.replace("Z", "+00:00")
        try:
            dt = datetime.fromisoformat(iso)
        except ValueError:
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S",
                        "%Y-%m-%d", "%b %d %H:%M:%S %Y GMT",
                        "%a, %d %b %Y %H:%M:%S %Z", "%m/%d/%Y", "%d/%m/%Y"):
                try:
                    dt = datetime.strptime(s, fmt)
                    break
                except ValueError:
                    continue
    if dt is None:
        return {"status": "error", "result": {"reason": "unparseable date: %s" % s[:40]}}
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    now = kwargs.get("_now")
    now = datetime.fromtimestamp(float(now), tz=timezone.utc) if now else datetime.now(timezone.utc)
    delta = now - dt
    secs = delta.total_seconds()
    past = secs >= 0
    secs = abs(secs)
    for unit, size in (("year", 31536000), ("month", 2592000), ("day", 86400),
                       ("hour", 3600), ("minute", 60)):
        if secs >= size:
            n = int(secs // size)
            ago = "%d %s%s %s" % (n, unit, "s" if n != 1 else "", "ago" if past else "from now")
            break
    else:
        ago = "just now"
    return {"status": "ok", "result": {
        "iso": dt.isoformat(),
        "utc_timestamp": dt.timestamp(),
        "age_hours": round(delta.total_seconds() / 3600.0, 2),
        "time_ago": ago,
    }}
