"""Executable skill: rewrite-tone

Use this skill to rewrite text in a target tone (e.g. professional, friendly, punchy, formal) while preserving meaning. Uses an LLM.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re


def skill(ctx, **kwargs):
    """Rewrite text in a target tone using an LLM."""
    
    # Validate required parameters
    text = kwargs.get("text")
    tone = kwargs.get("tone")
    
    if not text:
        return {
            "status": "error",
            "result": {"reason": "Missing required parameter: text"}
        }
    
    if not tone:
        return {
            "status": "error",
            "result": {"reason": "Missing required parameter: tone"}
        }
    
    # Ensure text and tone are strings
    if not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' must be a string"}
        }
    
    if not isinstance(tone, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'tone' must be a string"}
        }
    
    # Strip whitespace
    text = text.strip()
    tone = tone.strip()
    
    if not text:
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' cannot be empty"}
        }
    
    if not tone:
        return {
            "status": "error",
            "result": {"reason": "Parameter 'tone' cannot be empty"}
        }
    
    try:
        # Build the prompt for the LLM
        prompt = f"""Rewrite the following text in a {tone} tone. Preserve the original meaning and content exactly.

Original text:
{text}

Rewritten text in {tone} tone:"""
        
        # Call the LLM
        response = ctx.llm(prompt, max_tokens=2000)
        
        if not response:
            return {
                "status": "error",
                "result": {"reason": "LLM returned empty response"}
            }
        
        # Normalize the response - strip leading/trailing whitespace
        rewritten_text = response.strip()
        
        # Remove common preamble patterns if present
        lines = rewritten_text.split('\n')
        cleaned_lines = []
        
        for line in lines:
            stripped = line.strip()
            # Skip empty lines and common preamble lines
            if not stripped:
                continue
            if stripped.lower().startswith(('here', 'rewritten', 'tone:', 'the rewritten', 'revised')):
                # Check if it's a complete preamble line (ends with colon or is very short)
                if stripped.endswith(':') or len(stripped) < 20:
                    continue
            cleaned_lines.append(stripped)
        
        # Rejoin the cleaned lines
        rewritten_text = '\n'.join(cleaned_lines).strip()
        
        if not rewritten_text:
            return {
                "status": "error",
                "result": {"reason": "Failed to generate rewritten text"}
            }
        
        return {
            "status": "ok",
            "result": {
                "original_text": text,
                "rewritten_text": rewritten_text,
                "tone": tone
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Error during rewriting: {str(e)}"}
        }
