"""Autogenerated CLI wrapper for the 'utm-builder' skill. Do not edit by hand."""
import argparse
import json
import sys

sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED")
sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\ATEN")


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [x.strip() for x in str(v).split(",") if x.strip()]


def _as_json(v):
    return v if isinstance(v, (dict, list)) else json.loads(v)


class _Ctx:
    """Minimal SkillContext shim (mirrors ATEN skill_library.context.SkillContext)."""
    niche = "reviews"
    agent_id = "cli"

    def llm(self, prompt, model="groq/llama-3.3-70b-versatile", max_tokens=1000):
        try:
            sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\cost-optimizer")
            from empire_router import router
            return router.complete(prompt=prompt, task="skill_llm", max_tokens=max_tokens)
        except Exception as e:
            print(f"[ctx.llm] {e}", file=sys.stderr)
            return ""

    def http_get(self, url, timeout=30):
        import urllib.request
        req = urllib.request.Request(url, headers={"User-Agent": "empire-skill/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return {"status": r.status, "body": r.read().decode("utf-8", "ignore")}


def main():
    ap = argparse.ArgumentParser(description='Use this skill to append correctly-encoded UTM tracking parameters to a URL for campaign attribution (source, medium, campaign, term, content). Handles existing query strings and fragments. Deterministic, offline. Returns the tagged URL.')
    ap.add_argument("--url", default=None, required=True, help='Base URL')
    ap.add_argument("--source", default=None, required=True, help='utm_source')
    ap.add_argument("--medium", default=None, required=True, help='utm_medium')
    ap.add_argument("--campaign", default=None, required=True, help='utm_campaign')
    ap.add_argument("--term", default=None, required=False, help='utm_term')
    ap.add_argument("--content", default=None, required=False, help='utm_content')
    args = ap.parse_args()
    kwargs = {}
    if getattr(args, "url") is not None:
        kwargs["url"] = str(getattr(args, "url"))
    if getattr(args, "source") is not None:
        kwargs["source"] = str(getattr(args, "source"))
    if getattr(args, "medium") is not None:
        kwargs["medium"] = str(getattr(args, "medium"))
    if getattr(args, "campaign") is not None:
        kwargs["campaign"] = str(getattr(args, "campaign"))
    if getattr(args, "term") is not None:
        kwargs["term"] = str(getattr(args, "term"))
    if getattr(args, "content") is not None:
        kwargs["content"] = str(getattr(args, "content"))

    from utm_builder_skill import skill as _entry  # noqa
    result = _entry(_Ctx(), **kwargs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
