"""Executable skill: utm-builder

Use this skill to append correctly-encoded UTM tracking parameters to a URL for campaign attribution (source, medium, campaign, term, content). Handles existing query strings and fragments. Deterministic, offline. Returns the tagged URL.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    from urllib.parse import urlparse, urlencode, parse_qsl, urlunparse
    url = kwargs.get("url", "")
    source = kwargs.get("source"); medium = kwargs.get("medium"); campaign = kwargs.get("campaign")
    if not url or not source or not medium or not campaign:
        return {"status": "error", "result": {"reason": "url, source, medium, campaign are required"}}
    try:
        parts = urlparse(url if "://" in url else "https://" + url)
    except Exception as e:
        return {"status": "error", "result": {"reason": "invalid url: %s" % e}}
    q = dict(parse_qsl(parts.query))
    q["utm_source"] = source
    q["utm_medium"] = medium
    q["utm_campaign"] = campaign
    if kwargs.get("term"):
        q["utm_term"] = kwargs["term"]
    if kwargs.get("content"):
        q["utm_content"] = kwargs["content"]
    tagged = urlunparse(parts._replace(query=urlencode(q)))
    return {"status": "ok", "result": {"url": tagged}}
