"""Executable skill: extract-key-phrases

Use this skill to extract the most important key phrases / topics from a text as a short list. Uses an LLM. For tagging and SEO keyword discovery.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re


def skill(ctx, **kwargs):
    """
    Extract key phrases/topics from text using an LLM.
    Returns a list of important keywords for tagging and SEO discovery.
    """
    # Validate required parameter
    text = kwargs.get("text")
    if not text or not isinstance(text, str):
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' is required and must be a non-empty string"}
        }
    
    # Optionally allow customizing number of phrases (default 5-10)
    max_phrases = kwargs.get("max_phrases", 8)
    
    try:
        # Create prompt asking LLM to extract key phrases
        prompt = f"""Extract the {max_phrases} most important key phrases and topics from the following text. These will be used for tagging and SEO keyword discovery.

Return ONLY a JSON array of strings with the key phrases, no other text or explanation. Example format:
["phrase one", "phrase two", "phrase three"]

Text:
{text}"""
        
        # Call LLM
        response = ctx.llm(prompt, max_tokens=500)
        
        if not response or not isinstance(response, str):
            return {
                "status": "error",
                "result": {"reason": "LLM returned no valid response"}
            }
        
        # Parse the response - try to extract JSON array
        response = response.strip()
        
        # Look for JSON array in the response
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            try:
                phrases = json.loads(json_str)
            except json.JSONDecodeError:
                # Fallback: try to parse as-is
                phrases = json.loads(response)
        else:
            # Fallback: try direct JSON parse
            try:
                phrases = json.loads(response)
            except json.JSONDecodeError:
                return {
                    "status": "error",
                    "result": {"reason": "Could not parse LLM response as JSON array"}
                }
        
        # Validate and normalize result
        if not isinstance(phrases, list):
            return {
                "status": "error",
                "result": {"reason": "LLM response was not a JSON array"}
            }
        
        # Filter and clean phrases
        cleaned_phrases = []
        for phrase in phrases:
            if isinstance(phrase, str):
                cleaned = phrase.strip()
                # Remove common junk patterns
                if cleaned and len(cleaned) > 1 and not cleaned.lower().startswith(("here", "the list", "example")):
                    cleaned_phrases.append(cleaned)
        
        # Ensure we don't exceed requested count
        cleaned_phrases = cleaned_phrases[:max_phrases]
        
        if not cleaned_phrases:
            return {
                "status": "error",
                "result": {"reason": "No valid key phrases could be extracted"}
            }
        
        return {
            "status": "ok",
            "result": cleaned_phrases
        }
    
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"Extraction failed: {str(e)}"}
        }
