"""Executable skill: hex-to-rgb

Use this skill to convert a hex color (#rrggbb or #rgb) to RGB values and a css rgb() string. Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    h = (kwargs.get("hex", "") or "").strip().lstrip("#")
    if not re.fullmatch(r"[0-9a-fA-F]{6}|[0-9a-fA-F]{3}", h or ""):
        return {"status": "error", "result": {"reason": "hex must be 3 or 6 hex digits"}}
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return {"status": "ok", "result": {"hex": "#" + h.lower(), "rgb": [r, g, b],
        "css": "rgb(%d, %d, %d)" % (r, g, b)}}
