"""Executable skill: levenshtein-distance

Use this skill to compute the Levenshtein edit distance between two strings plus a 0-1 similarity ratio. Deterministic, offline. For fuzzy matching and typo detection.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    a = kwargs.get("a", ""); b = kwargs.get("b", "")
    if not isinstance(a, str) or not isinstance(b, str):
        return {"status": "error", "result": {"reason": "a and b must be strings"}}
    if a == b:
        return {"status": "ok", "result": {"distance": 0, "ratio": 1.0}}
    la, lb = len(a), len(b)
    prev = list(range(lb + 1))
    for i in range(1, la + 1):
        cur = [i] + [0] * lb
        for j in range(1, lb + 1):
            cost = 0 if a[i-1] == b[j-1] else 1
            cur[j] = min(prev[j] + 1, cur[j-1] + 1, prev[j-1] + cost)
        prev = cur
    dist = prev[lb]
    maxlen = max(la, lb)
    return {"status": "ok", "result": {"distance": dist,
        "ratio": round(1 - dist / maxlen, 4) if maxlen else 1.0}}
