"""Executable skill: humanize-duration

Use this skill to convert a number of seconds into a human duration like '2h 5m 30s'. Deterministic, offline. For run-times, ETAs, video lengths.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    try:
        secs = float(kwargs.get("seconds"))
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "seconds must be numeric"}}
    neg = secs < 0
    secs = int(abs(secs))
    units = [("d", 86400), ("h", 3600), ("m", 60), ("s", 1)]
    parts = []
    for label, size in units:
        if secs >= size:
            n = secs // size
            secs -= n * size
            parts.append("%d%s" % (n, label))
    text = " ".join(parts) if parts else "0s"
    if neg:
        text = "-" + text
    return {"status": "ok", "result": {"human": text}}
