"""Executable skill: suggest-titles

Use this skill to generate N catchy, SEO-aware title options for an article given its topic or first paragraph. Uses an LLM.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re

def skill(ctx, **kwargs):
    """
    Generate N catchy, SEO-aware title options for an article.
    
    Args:
        ctx: Agent context with LLM access
        **kwargs: 
            - text (required): Input text (topic or first paragraph)
            - count (optional, default 5): Number of titles to generate
    
    Returns:
        {"status": "ok", "result": [title1, title2, ...]}
        or
        {"status": "error", "result": {"reason": "..."}}
    """
    
    # Validate required parameters
    text = kwargs.get("text")
    if not text:
        return {
            "status": "error",
            "result": {"reason": "Missing required parameter: text"}
        }
    
    if not isinstance(text, str) or not text.strip():
        return {
            "status": "error",
            "result": {"reason": "Parameter 'text' must be a non-empty string"}
        }
    
    # Get count parameter with default
    count = kwargs.get("count", 5)
    try:
        count = int(count)
        if count < 1 or count > 50:
            count = 5
    except (ValueError, TypeError):
        count = 5
    
    # Build the prompt
    prompt = f"""Generate exactly {count} catchy, SEO-optimized article titles based on the following input text.

Input text:
{text.strip()}

Requirements:
- Generate exactly {count} titles
- Each title should be catchy and engaging
- Titles should be SEO-friendly with relevant keywords
- Keep titles between 50-70 characters when possible
- Vary the style and approach across titles
- Number each title (1., 2., etc.)

Output format: Return only the numbered list of titles, one per line. Do not include explanations."""
    
    try:
        response = ctx.llm(prompt, max_tokens=1000)
    except Exception as e:
        return {
            "status": "error",
            "result": {"reason": f"LLM call failed: {str(e)}"}
        }
    
    if not response or not isinstance(response, str):
        return {
            "status": "error",
            "result": {"reason": "LLM returned empty or invalid response"}
        }
    
    # Parse the response into a list of titles
    lines = response.strip().split("\n")
    titles = []
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        
        # Remove numbering (1., 1), etc.) and bullet markers
        cleaned = re.sub(r"^[\d]+[\.\)]\s*", "", line)
        cleaned = re.sub(r"^[-*•]\s*", "", cleaned)
        cleaned = cleaned.strip()
        
        # Filter out common preamble/explanation text
        if cleaned.lower().startswith("here are"):
            continue
        if cleaned.lower().startswith("the titles are"):
            continue
        if not cleaned:
            continue
        
        titles.append(cleaned)
    
    # Enforce exact count
    titles = titles[:count]
    
    # Check if we got enough titles
    if len(titles) == 0:
        return {
            "status": "error",
            "result": {"reason": "Could not parse any valid titles from LLM response"}
        }
    
    return {
        "status": "ok",
        "result": titles
    }
