"""Executable skill: estimate-tokens

Use this skill to approximate the LLM token count of a text before an API call, for cost/budget guarding. Averages two estimators (~4 chars/token and ~0.75 tokens/word). Deterministic, offline, no tokenizer dependency. Not exact, but reliable for gating oversized prompts.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    chars = len(text)
    words = len(re.findall(r"\S+", text))
    # Two independent estimators; average them. ~4 chars/token (OpenAI rule of
    # thumb) and ~0.75 tokens/word. Deterministic upper-ish estimate.
    by_chars = chars / 4.0
    by_words = words / 0.75
    est = int(round((by_chars + by_words) / 2.0))
    return {"status": "ok", "result": {
        "estimated_tokens": est,
        "chars": chars, "words": words,
        "by_chars": int(round(by_chars)), "by_words": int(round(by_words)),
        "note": "approximate; ~4 chars/token averaged with ~0.75 tokens/word"}}
