"""Executable skill: uuid-check

Use this skill to validate whether a string is a well-formed UUID (v1-v5) and report its version. Deterministic, offline. For ID validation.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    v = (kwargs.get("value", "") or "").strip()
    pat = r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    valid = bool(re.match(pat, v))
    ver = int(v[14], 16) if valid else None
    return {"status": "ok", "result": {"valid": valid, "version": ver}}
