"""Executable skill: keyword-density

Use this skill to compute how often a target keyword (or phrase) appears in a text, as a raw count and as a percentage of total words (0-100). Case-insensitive, whole-word matching, supports multi-word phrases. Deterministic, offline. Flags over-optimization above 3%.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    keyword = (kwargs.get("keyword") or "").strip()
    if not text or not keyword:
        return {"status": "error", "result": {"reason": "text and keyword are required"}}
    words = re.findall(r"\b\w+\b", text.lower())
    total = len(words)
    if total == 0:
        return {"status": "ok", "result": {"count": 0, "density_pct": 0.0, "total_words": 0}}
    kw_words = re.findall(r"\b\w+\b", keyword.lower())
    if len(kw_words) == 1:
        count = words.count(kw_words[0])
    else:
        count = 0
        for i in range(len(words) - len(kw_words) + 1):
            if words[i:i + len(kw_words)] == kw_words:
                count += 1
    occurrences_of_words = count * len(kw_words)
    density = round(100.0 * occurrences_of_words / total, 2)
    return {"status": "ok", "result": {
        "count": count,
        "total_words": total,
        "density_pct": density,
        "over_optimized": density > 3.0,
    }}
