"""Executable skill: categorize-text

Use this skill to assign the single best category to a text from a provided list of candidate categories, with a confidence note. Uses an LLM. For routing, tagging, and triage.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
import json
import re
from typing import Any, Dict, List

def skill(ctx, **kwargs) -> Dict[str, Any]:
    # Validate required parameters
    text = kwargs.get('text')
    categories_raw = kwargs.get('categories')
    
    if not text or not categories_raw:
        return {
            "status": "error",
            "result": {
                "reason": "Missing required parameter(s): text and/or categories must be provided"
            }
        }
    
    # Normalize categories to a list
    if isinstance(categories_raw, str):
        categories = [c.strip() for c in categories_raw.split(',') if c.strip()]
    elif isinstance(categories_raw, list):
        categories = [str(c).strip() for c in categories_raw if str(c).strip()]
    else:
        return {
            "status": "error",
            "result": {
                "reason": "categories must be a list or comma-separated string"
            }
        }
    
    if len(categories) < 2:
        return {
            "status": "error",
            "result": {
                "reason": "At least two candidate categories are required"
            }
        }
    
    # Build prompt for LLM
    categories_str = ', '.join(categories)
    prompt = f"""Classify the following text into exactly one category from this list: [{categories_str}].
Only output the exact category name, nothing else. Then on a new line output a confidence score from 0.0 to 1.0.
Format:
CATEGORY: <category name>
CONFIDENCE: <score>

Text: {text}"""
    
    try:
        response = ctx.llm(prompt, max_tokens=200)
        if not response:
            return {
                "status": "error",
                "result": {
                    "reason": "LLM returned empty response"
                }
            }
        
        # Parse response
        category_line = None
        confidence_line = None
        
        for line in response.strip().split('\n'):
            line = line.strip()
            if line.upper().startswith('CATEGORY:'):
                category_line = line.split(':', 1)[1].strip() if ':' in line else ''
            elif line.upper().startswith('CONFIDENCE:'):
                confidence_str = line.split(':', 1)[1].strip() if ':' in line else ''
                try:
                    confidence = float(confidence_str)
                    if 0.0 <= confidence <= 1.0:
                        confidence_line = confidence
                except (ValueError, TypeError):
                    confidence_line = 0.5  # fallback if parsing fails
        
        # Validate category
        if not category_line or category_line not in categories:
            # Try case-insensitive matching
            category_lower = category_line.lower() if category_line else ''
            match = [c for c in categories if c.lower() == category_lower]
            if match:
                category_line = match[0]
            else:
                return {
                    "status": "error",
                    "result": {
                        "reason": f"LLM returned category '{category_line}' which is not in the allowed categories list: {categories_str}"
                    }
                }
        
        if confidence_line is None:
            confidence_line = 0.5
        
        result = {
            "category": category_line,
            "confidence": round(confidence_line, 2)
        }
        
        return {
            "status": "ok",
            "result": result
        }
        
    except Exception as e:
        return {
            "status": "error",
            "result": {
                "reason": f"Failed to categorize text: {str(e)}"
            }
        }
