"""Executable skill: json-validator

Use this skill to check whether a string is valid JSON and describe its shape: top-level type, key count (objects) or length (arrays), and the specific parse error with line/column if invalid. Deterministic, offline. Great for validating LLM output before using it.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import json
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        return {"status": "ok", "result": {
            "valid": False, "error": e.msg, "line": e.lineno, "column": e.colno}}
    top = type(data).__name__
    shape = {"valid": True, "top_level_type": top}
    if isinstance(data, dict):
        shape["key_count"] = len(data)
        shape["keys"] = list(data.keys())[:20]
    elif isinstance(data, list):
        shape["length"] = len(data)
    return {"status": "ok", "result": shape}
