"""Executable skill: word-wrap

Use this skill to wrap text to a given column width (default 80), preserving words. Deterministic, offline. For plain-text formatting and emails.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import textwrap
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    try:
        width = int(kwargs.get("width") or 80)
    except (TypeError, ValueError):
        width = 80
    wrapped = textwrap.fill(text, width=max(1, width))
    return {"status": "ok", "result": {"text": wrapped,
        "lines": wrapped.count(chr(10)) + 1 if wrapped else 0}}
