"""Executable skill: alt-text-check

Use this skill to audit image alt text in markdown: counts images, missing alt, and alt over 125 chars. Deterministic, offline. For accessibility + SEO image compliance.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    md = kwargs.get("markdown", "")
    if not isinstance(md, str):
        return {"status": "error", "result": {"reason": "markdown must be a string"}}
    imgs = re.findall(r"!\[([^\]]*)\]\([^)]*\)", md)
    missing = sum(1 for a in imgs if not a.strip())
    too_long = [a for a in imgs if len(a) > 125]
    return {"status": "ok", "result": {"images": len(imgs),
        "missing_alt": missing, "alt_too_long": len(too_long),
        "all_ok": missing == 0 and not too_long}}
