"""Executable skill: extract-domains

Use this skill to extract and normalize the domains of all URLs in a text: strips www, ports, and paths, de-duplicates, and counts links per domain. Deterministic, offline. Ideal for auditing outbound/affiliate links in an article or checking link diversity.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    from urllib.parse import urlparse
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    urls = re.findall(r"https?://[^\s<>\"\)]+", text)
    seen, domains, by_domain = set(), [], {}
    for u in urls:
        try:
            host = urlparse(u).netloc.lower()
        except Exception:
            continue
        if host.startswith("www."):
            host = host[4:]
        host = host.split(":")[0]
        if not host:
            continue
        by_domain[host] = by_domain.get(host, 0) + 1
        if host not in seen:
            seen.add(host)
            domains.append(host)
    return {"status": "ok", "result": {
        "domains": domains, "count": len(domains),
        "url_count": len(urls),
        "by_domain": dict(sorted(by_domain.items(), key=lambda x: -x[1]))}}
