"""Executable skill: csv-to-json

Use this skill to convert CSV text into a list of JSON records, auto-detecting the delimiter (comma, semicolon, tab, or pipe) and using the first row as headers. Handles ragged rows. Deterministic, offline. The reliable first step before processing spreadsheet exports.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import csv, io
    text = kwargs.get("csv", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "csv text is required"}}
    delimiter = kwargs.get("delimiter")
    if not delimiter:
        sample = text[:2048]
        try:
            delimiter = csv.Sniffer().sniff(sample, delimiters=",;\t|").delimiter
        except Exception:
            delimiter = ","
    reader = csv.reader(io.StringIO(text), delimiter=delimiter)
    try:
        rows = [r for r in reader if r]
    except Exception as e:
        return {"status": "error", "result": {"reason": "csv parse error: %s" % e}}
    if not rows:
        return {"status": "ok", "result": {"records": [], "count": 0, "columns": []}}
    header = [h.strip() for h in rows[0]]
    records = []
    for r in rows[1:]:
        rec = {header[i] if i < len(header) else ("col_%d" % i): (r[i] if i < len(r) else None)
               for i in range(max(len(header), len(r)))}
        records.append(rec)
    return {"status": "ok", "result": {
        "records": records, "count": len(records),
        "columns": header, "delimiter": delimiter}}
