"""Autogenerated CLI wrapper for the 'csv-to-json' skill. Do not edit by hand."""
import argparse
import json
import sys

sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED")
sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\ATEN")


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [x.strip() for x in str(v).split(",") if x.strip()]


def _as_json(v):
    return v if isinstance(v, (dict, list)) else json.loads(v)


class _Ctx:
    """Minimal SkillContext shim (mirrors ATEN skill_library.context.SkillContext)."""
    niche = "ai"
    agent_id = "cli"

    def llm(self, prompt, model="groq/llama-3.3-70b-versatile", max_tokens=1000):
        try:
            sys.path.insert(0, r"C:\D\Claude Code Projects\_SHARED\cost-optimizer")
            from empire_router import router
            return router.complete(prompt=prompt, task="skill_llm", max_tokens=max_tokens)
        except Exception as e:
            print(f"[ctx.llm] {e}", file=sys.stderr)
            return ""

    def http_get(self, url, timeout=30):
        import urllib.request
        req = urllib.request.Request(url, headers={"User-Agent": "empire-skill/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return {"status": r.status, "body": r.read().decode("utf-8", "ignore")}


def main():
    ap = argparse.ArgumentParser(description='Use this skill to convert CSV text into a list of JSON records, auto-detecting the delimiter (comma, semicolon, tab, or pipe) and using the first row as headers. Handles ragged rows. Deterministic, offline. The reliable first step before processing spreadsheet exports.')
    ap.add_argument("--csv", default=None, required=True, help='CSV text to parse')
    ap.add_argument("--delimiter", default=None, required=False, help='Force a delimiter (default: auto-detect)')
    args = ap.parse_args()
    kwargs = {}
    if getattr(args, "csv") is not None:
        kwargs["csv"] = str(getattr(args, "csv"))
    if getattr(args, "delimiter") is not None:
        kwargs["delimiter"] = str(getattr(args, "delimiter"))

    from csv_to_json_skill import skill as _entry  # noqa
    result = _entry(_Ctx(), **kwargs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
