"""Executable skill: extract-hashtags

Use this skill to extract hashtags from social text: pulls #tags, de-duplicates case-insensitively, drops numeric-only tags, and returns them both with and without the # prefix. Deterministic, offline. Useful for auditing or reusing the tag set of a post.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    raw = re.findall(r"(?<!\w)#([A-Za-z0-9_]+)", text)
    seen, tags = set(), []
    for h in raw:
        lo = h.lower()
        if lo not in seen and not h.isdigit():
            seen.add(lo)
            tags.append(h)
    return {"status": "ok", "result": {
        "hashtags": ["#" + t for t in tags],
        "bare": tags, "count": len(tags)}}
