"""Executable skill: initials

Use this skill to get the initials of a name/phrase (first letter of each word, uppercased, capped at max). Deterministic, offline. For avatars/monograms.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    text = (kwargs.get("text", "") or "").strip()
    if not text:
        return {"status": "error", "result": {"reason": "text is required"}}
    words = [w for w in re.split(r"\s+", text) if w and w[0].isalnum()]
    try:
        maxlen = int(kwargs.get("max") or 3)
    except (TypeError, ValueError):
        maxlen = 3
    initials = "".join(w[0].upper() for w in words)[:maxlen]
    return {"status": "ok", "result": {"initials": initials}}
