"""Executable skill: json-format

Use this skill to pretty-print or minify a JSON string (mode=pretty|minify, optional sort_keys). Validates first. Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import json as _j
    text = kwargs.get("text", "")
    mode = (kwargs.get("mode") or "pretty").lower()
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    try:
        data = _j.loads(text)
    except Exception as e:
        return {"status": "error", "result": {"reason": "invalid JSON: %s" % e}}
    if mode == "minify":
        out = _j.dumps(data, separators=(",", ":"), ensure_ascii=False)
    else:
        out = _j.dumps(data, indent=2, ensure_ascii=False, sort_keys=bool(kwargs.get("sort_keys")))
    return {"status": "ok", "result": {"output": out, "mode": mode}}
