"""Executable skill: roman-numeral

Use this skill to convert an integer (1-3999) to a Roman numeral, or a Roman numeral back to an integer (to=roman|int). Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    val = kwargs.get("value")
    to = (kwargs.get("to") or "roman").lower()
    table = [(1000,"M"),(900,"CM"),(500,"D"),(400,"CD"),(100,"C"),(90,"XC"),
             (50,"L"),(40,"XL"),(10,"X"),(9,"IX"),(5,"V"),(4,"IV"),(1,"I")]
    if to == "int":
        s = str(val).upper().strip()
        romans = {"M":1000,"D":500,"C":100,"L":50,"X":10,"V":5,"I":1}
        if not s or any(c not in romans for c in s):
            return {"status": "error", "result": {"reason": "invalid roman numeral"}}
        total = 0; prev = 0
        for c in reversed(s):
            cur = romans[c]
            total += -cur if cur < prev else cur
            prev = cur
        return {"status": "ok", "result": {"int": total}}
    try:
        n = int(val)
    except (TypeError, ValueError):
        return {"status": "error", "result": {"reason": "value must be an integer"}}
    if not (1 <= n <= 3999):
        return {"status": "error", "result": {"reason": "roman supports 1-3999"}}
    out = []
    for v, sym in table:
        while n >= v:
            out.append(sym); n -= v
    return {"status": "ok", "result": {"roman": "".join(out)}}
