"""Autogenerated CLI wrapper for the 'word-frequency' skill. Do not edit by hand."""
import argparse
import json
import os
import sys

# Make _SHARED importable IF present (only needed for skills that use ctx.llm /
# ctx.http_get — deterministic skills don't need it). Resolve portably: the
# EMPIRE_ROOT env var, then common empire locations, then a no-op. NEVER hardcode
# a single machine's absolute path — a downloaded skill must run anywhere.
for _root in filter(None, [
        os.environ.get("EMPIRE_ROOT"),
        os.environ.get("EMPIRE_SHARED"),
        "/opt", "/opt/_SHARED",
        r"C:\D\Claude Code Projects"]):
    _shared = os.path.join(_root, "_SHARED") if os.path.basename(_root) != "_SHARED" else _root
    if os.path.isdir(_shared):
        sys.path.insert(0, _shared)
        _aten = os.path.join(_shared, "ATEN")
        if os.path.isdir(_aten):
            sys.path.insert(0, _aten)
        break


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on")


def _as_list(v):
    if isinstance(v, list):
        return v
    return [x.strip() for x in str(v).split(",") if x.strip()]


def _as_json(v):
    return v if isinstance(v, (dict, list)) else json.loads(v)


class _Ctx:
    """Minimal SkillContext shim (mirrors ATEN skill_library.context.SkillContext)."""
    niche = "publishing"
    agent_id = "cli"

    def llm(self, prompt, model="groq/llama-3.3-70b-versatile", max_tokens=1000):
        try:
            for _p in sys.path[:]:
                _co = os.path.join(_p, "cost-optimizer")
                if os.path.isdir(_co):
                    sys.path.insert(0, _co)
                    break
            from empire_router import router
            return router.complete(prompt=prompt, task="skill_llm", max_tokens=max_tokens)
        except Exception as e:
            print(f"[ctx.llm] {e}", file=sys.stderr)
            return ""

    def http_get(self, url, timeout=30):
        import urllib.request
        req = urllib.request.Request(url, headers={"User-Agent": "empire-skill/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return {"status": r.status, "body": r.read().decode("utf-8", "ignore")}


def main():
    ap = argparse.ArgumentParser(description='Use this skill to get the most frequent words in a text: tokenizes, lowercases, drops common stopwords (optional), and returns the top-N words with counts plus total/unique word counts. Deterministic, offline. For content analysis, keyword discovery, and tag suggestions.')
    ap.add_argument("--text", default=None, required=True, help='Text to analyze')
    ap.add_argument("--top", default=None, required=False, help='How many top words (default 10)')
    ap.add_argument("--include_stopwords", default=None, required=False, help='Include common stopwords (default false)')
    args = ap.parse_args()
    kwargs = {}
    if getattr(args, "text") is not None:
        kwargs["text"] = str(getattr(args, "text"))
    if getattr(args, "top") is not None:
        kwargs["top"] = float(getattr(args, "top"))
    if getattr(args, "include_stopwords") is not None:
        kwargs["include_stopwords"] = _as_bool(getattr(args, "include_stopwords"))

    from word_frequency_skill import skill as _entry  # noqa
    result = _entry(_Ctx(), **kwargs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    main()
