"""Executable skill: word-frequency

Use this skill to get the most frequent words in a text: tokenizes, lowercases, drops common stopwords (optional), and returns the top-N words with counts plus total/unique word counts. Deterministic, offline. For content analysis, keyword discovery, and tag suggestions.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    import re
    from collections import Counter
    text = kwargs.get("text", "")
    if not isinstance(text, str) or not text.strip():
        return {"status": "error", "result": {"reason": "text is required"}}
    try:
        top = int(kwargs.get("top") or 10)
    except (TypeError, ValueError):
        top = 10
    stop = {"the","a","an","and","or","but","of","to","in","on","for","is",
            "are","was","were","be","this","that","it","as","at","by","with"}
    words = re.findall(r"[a-z0-9]+", text.lower())
    if kwargs.get("include_stopwords"):
        filtered = words
    else:
        filtered = [w for w in words if w not in stop]
    counts = Counter(filtered)
    return {"status": "ok", "result": {
        "total_words": len(words),
        "unique_words": len(set(words)),
        "top": [{"word": w, "count": c} for w, c in counts.most_common(top)]}}
