"""Executable skill: smart-truncate

Use this skill to truncate text to a max length at a word boundary with an ellipsis, without cutting words in half. Ideal for meta descriptions (155 chars), social previews, and card summaries. Deterministic, offline.

Auto-generated by SkillForge. Entry: skill(ctx, **kwargs).
"""
def skill(ctx, **kwargs):
    text = kwargs.get("text", "")
    if not isinstance(text, str):
        return {"status": "error", "result": {"reason": "text must be a string"}}
    try:
        limit = int(kwargs.get("max_length") or 155)
    except (TypeError, ValueError):
        limit = 155
    text = " ".join(text.split())
    if len(text) <= limit:
        return {"status": "ok", "result": text}
    cut = text[:max(0, limit - 1)].rsplit(" ", 1)[0].rstrip(",.;:!?-")
    return {"status": "ok", "result": (cut + "…") if cut else text[:limit]}
